project:
  type: website
  preview:
    port: 7567
  render:
    - "./*.qmd"
    - "slides/*.qmd"
    - "about/index.qmd"
  resources:
    - slides

website:
  title: "Level Up with Shiny for R"
  description: "Take your Shiny skills to the next level."
  site-url: https://posit-conf-2024.github.io/level-up-shiny

  favicon: assets/posit-conf-favicon.png
  twitter-card:
    creator: "@grrrck"
    site: "@posit-dev"
    image: assets/open-graph-card-2.png
  open-graph:
    image: assets/open-graph-card-2.png

  # FIXME: remove announcement
  announcement:
    icon: cone-striped
    dismissible: true
    content: This page is under active development. **See you at the workshop!**
    type: warning
  
  page-footer: |
    <a href="https:://posi.it/conf-event-portal">posit::conf(2024)</a>
  
  repo-url: https://github.com/posit-conf-2024/level-up-shiny
  repo-subdir: website
  repo-actions: [edit, issue]
  
  navbar:
    title: "Level Up Shiny"
    foreground: black
    background: white
    left:
      - href: index.qmd
        text: Home
      - href: workshop.qmd
        text: Workshop
      - href: setup.qmd
        text: Setup
      - href: about/index.qmd
        text: Team
    tools:
      - icon: github
        href: https://github.com/posit-conf-2024/level-up-shiny
        aria-label: Workshop materials
      - icon: pc-display
        href: https://posit.cloud/spaces/517274/
        aria-label: Posit Conf Workspace
  
  page-navigation: true
  
  sidebar:
    - id: workshop
      style: docked
      type: light
      background: light
      foreground: dark
      contents:
        - workshop.qmd
        - text: '<div class="sidebar-divider font-monospace">Morning 1</div>'
        - workshop-01.qmd
        - workshop-02.qmd
        - workshop-03-break.qmd
        - text: '<div class="sidebar-divider font-monospace">Morning 2</div>'
        - workshop-04.qmd
        - workshop-05.qmd
        - workshop-06.qmd
        - workshop-07-break.qmd
        - text: '<div class="sidebar-divider font-monospace">Afternoon 1</div>'
        - workshop-08.qmd
        - workshop-09.qmd
        - workshop-10.qmd
        - workshop-11-break.qmd
        - text: '<div class="sidebar-divider font-monospace">Afternoon 2</div>'
        - workshop-12.qmd
        - workshop-13.qmd

format:
  html:
    theme: [zephyr, styles.scss]
    css:
      - auto-dark-mode.css
    toc: true
    lightbox: true
    include-before-body:
      - text: <script>document.querySelector('.navbar').dataset.bsTheme = 'light';</script>
      - text: |
          <script>
            const icons = document.querySelectorAll(".quarto-navigation-tool")
            icons.forEach(icon => {
              icon.dataset.bsToggle = "tooltip"
              icon.dataset.bsPlacement = "bottom"
              icon.dataset.bsTitle = icon.getAttribute("aria-label")
              new bootstrap.Tooltip(icon)
            })
          </script>

filters:
  - shinylive

editor:
  render-on-save: true