on:
  push:
    branches:
      - main
    paths:
      - "website/**"
      - ".github/workflows/publish.yml"

name: Render and Publish

permissions:
    contents: write
    pages: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: 📘 Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: 1.5.55
          tinytex: false

      # - name: 🆙 Setup R
      #   uses: r-lib/actions/setup-r@v2

      # - name: 📦 Install dependencies with renv
      #   uses: r-lib/actions/setup-renv@v2
      #   env:
      #     RENV_CONFIG_PAK_ENABLED: true
      #     cache-version: 2

      - name: 📰 Render and Publish to GitHub Pages
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
          path: website
